server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: videohoster-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/videohoster
    username: postgres
    password: linkinpark08

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect